HEIGHT = 600

LANE_WIDTH = 100
CAR_HEIGHT = 50
CAR_WIDTH = 20
STREET_MIDDLE_WIDTH = 8
DOTTED_LINE_WIDTH = 2
LIGHT_HEIGHT = 30
LIGHT_RADIUS = 15
LIGHT_MARGIN = 10
PEDESTRIAN_DIAMETER = 10

DIRECTION_DOWN = 0
DIRECTION_UP = 1
DIRECTION_LEFT = 2
DIRECTION_RIGHT = 3

LIMIT_OF_PEDESTRIANS = 5
PEDESTRIAN_MIN_SPEED = 15
PEDESTRIAN_MAX_SPEED = 25

RANDOM_STOP_MAX = 20
RANDOM_PEDESTRIAN_MAX = 7

LANES_PER_STREET = 2
NUMBER_OF_STREETS = 2

COLOR_STREET_GRAY = "#686466"
COLOR_WHITE = "#FFFFFF"
COLOR_BLACK = "#000000"
COLOR_YELLOW = "#FFFF00"
COLOR_GREEN = "#00FF00"
COLOR_RED = "#FF0000"
COLOR_BLUE = "#0000FF"

GREEN_LIGHT = 0
YELLOW_LIGHT = 1
RED_LIGHT = 2
YELLOW_LIGHT_DURATION = 3
LIGHT_POSITION = (HEIGHT - LIGHT_HEIGHT)/2
