HEIGHT = 600

COMPUTER_COLOR = "#1abc9c"
PEDESTRIAN_COLOR = "#2ecc71"
INTELIGENT_COLOR = "#3498db"
COLOR_STREET_GRAY = "#686466"
COLOR_WHITE = "#FFFFFF"
COLOR_BLACK = "#000000"
COLOR_YELLOW = "#FFFF00"
COLOR_GREEN = "#00FF00"
COLOR_RED = "#FF0000"
COLOR_BLUE = "#0000FF"

LANES = 4
LANE_WIDTH = 100
DOTTED_LINE_WIDTH = 2

CAR_HEIGHT = 50
CAR_WIDTH = 20

RANDOM_STOP_MAX = 20
LIGHT_HEIGHT = 20
LIGHT_RADIUS = 10
LIGHT_MARGIN = 5
YELLOW_LIGHT_DURATION = 3

GREEN_LIGHT = 0
YELLOW_LIGHT = 1
RED_LIGHT = 2
LIGHT_POSITION = (HEIGHT - LIGHT_HEIGHT)/2

RANDOM_PEDESTRIAN_MAX = 7
LIMIT_OF_PEDESTRIANS = 5
PEDESTRIAN_DIAMETER = 10
PEDESTRIAN_MIN_SPEED = 15
PEDESTRIAN_MAX_SPEED = 25

DIRECTION_DOWN = 0
DIRECTION_UP = 1
DIRECTION_LEFT = 2
DIRECTION_RIGHT = 3

